# Generated by Django 6.0 on 2025-12-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('full_name', models.IntegerField(max_length=150)),
                ('department', models.IntegerField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.IntegerField(max_length=50)),
                ('address', models.IntegerField(max_length=150)),
            ],
        ),
    ]
