# Generated by Django 5.2.7 on 2025-12-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
